CREATE TABLE students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    course VARCHAR(100) NOT NULL,
    address TEXT NOT NULL,
    photo VARCHAR(255) NOT NULL DEFAULT '',
    date_registered TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
